spring:
  application:
    name: activityservice

  data:
    mongodb:
      uri: ${DB_URL}

server:
  port: ${PORT:8080}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true

  instance:
    prefer-ip-address: true

Internal:
  gateway:
    key: ${ACTIVITY-SERVICE-INTERNAL-SECURITY-KEY}