spring:
  application:
    name: userservice

  datasource:
    url: jdbc:postgresql://ep-bitter-math-a1k4twcv.ap-southeast-1.aws.neon.tech/fitness_users?sslmode=require
    username: neondb_owner
    password: npg_u24JtoOvMBCh

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

#server:
#  port: 8081

#For Render
server:
  port: ${PORT:8080}

